app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();



Route::get('/home', 'HomeController@index');
Route::get('/aboutus', 'aboutusController@index');
Route::get('/courses', 'coursesController@index');
Route::resource('contact', 'contactController');
Route::resource('signup', 'studentController');
Route::resource('signup2', 'student2Controller');
Route::resource('interest_courses', 'interest_courses');
Route::get('paymentConfirmation', 'paymentConfirmationController@index');
Route::get('paymentSuccess', 'paymentConfirmationController@success');
Route::get('paymentRejected', 'paymentConfirmationController@rejected');
Route::get('paymentProcessed', 'paymentConfirmationController@proccesed');



Route::group(['middleware' => ['auth','admin']], function () {
    Route::resource('paymentRequest','paymentRequestController');

    /* Route::resource('forms','FormController');
    Route::get('studentslist','listController@students');
    Route::get('teacherslist','listController@teachers');
    Route::get('asessorslist','listController@assesors');
    Route::get('courses_shedule','listController@courses_shedule');
    //Route::resource('people','peopleController');
    Route::resource('students','studentsController');
    Route::get('students/enrolment/{id}','studentsController@enrolment');
    Route::resource('teachers','teachersController');
    Route::resource('courses_shedule','courses_sheduleController');
    Route::resource('enrolments','enrolmentController');
    //Route::get('students/enrolment/{id}','studentsController@enrolment'); */
});

Route::group(['middleware' => ['auth','assesor']], function () {
    
    Route::get('studentslist','listController@students');
    Route::resource('students','studentsController',['except'=>'create','edit','update']);
    //Route::get('students/enrolment/{id}','studentsController@enrolment');
});

app/Models/enrolment.php
<?php

namespace oasis\Model;

use Illuminate\Database\Eloquent\Model;

class enrolment extends Model
{
    protected $table="enrolments";
    protected $filable=['course'];

    public function scopeName($query){
    	$query->select('enrolments.id as registration','lastname','id_types.name as id_type','identification',
    		'students.name as firstname','courses.name as course','courses.standar_price as s_price',
    		'payment_statuses.name as payment_status')
        ->join('students','students.id','=','enrolments.student')
        ->join('courses','courses.id','=','enrolments.course')
        ->join('payment_statuses','payment_statuses.id','=','enrolments.payment_status')
        ->join('id_types','id_types.id','=','students.id_type');
    }

    public function course(){
    	return $this->bellongsTo(course::class);
    }
    public function student(){
    	return $this->bellongsTo(student::class);
    }
    public function payment_status(){
    	return $this->bellongsTo(payment_status::class);
    }

}

app/Http/Controllers/enrolmentController.php
<?php

namespace oasis\Http\Controllers;

use Illuminate\Http\Request;

use oasis\Http\Requests;

use oasis\User;
use oasis\enrolment;
use oasis\Models\course;
use oasis\Models\student;

use \PDF;

class enrolmentController extends Controller
{
    public function index(){
    	dd($id);

    	//$enrolment=enrolment::name()->get();
    	//return view('enrolments.index',compact('enrolment'));
    }

    public function show($id){
    	return $id;
    }


    public function create($id){
    	dd($id);
    	//$student=student::name()->get();
    	//$course=course::all();
    	//return view('enrolments.create',compact('course','student'));
    }


}

resources/views/enrolments/baseForm.blade.php
<h2>DATOS PERSONALES</h2>
    <table class='table' id='myTable'>

        <tbody>
            @foreach($student as $field)<tr>
            
           <tr><th>Nombre completo:</td><td>{{ $field->name }} {{ $field->lastname }}</td></tr>
           <tr><th>Identificación:</th><td>{{ $field->id_type }} No. {{ $field->identification }}</td></tr>
           <tr><th>Teléfono principal</th><td>{{ $field->main_phone }}</td></tr>
           <tr><th>Teléfono secundario</th><td>{{ $field->sec_phone }}</td></tr>
           <tr><th>Correo electrónico</th><td>{{ $field->email }}</td></tr>
           <tr><th>Cursos de interés</th><td>{{ $field->interest_courses }}</td></tr>
           
            
            </tr>
            @endforeach
        </tbody>        
    </table>



<div class="form-group{{ $errors->has('identification') ? ' has-error' : '' }}">
    <label for='identification' class='col-md-3 control-label'>Identificación</label>
    <div class='col-md-9'>
    <input type='text' id='identification' name='identification' class='form-control' value="{{isset($enrolment)?$enrolment->identification:old('identification')}}">
     @if ($errors->has('identification'))
        <span class='help-block'><strong>{{ $errors->first('identification') }}</strong></span>
    @endif
    </div>
</div>

<div class="form-group{{ $errors->has('course') ? ' has-error' : '' }}">
    <label for='course' class='col-md-3 control-label'>Curso</label>
    <div class='col-md-9'>
   <select name='course' class='form-control'>
            @foreach($course as $field)
            @if((isset($enrolment)&&$enrolment->course==$field->id)||$field->id==old('course'))
            <option value="{{$field->id}}" selected>
            @else
            <option value="{{$field->id}}">
            @endif   
                {{$field->name}}</option>
            @endforeach
       </select>
            @if ($errors->has('course'))
        <span class='help-block'><strong>{{ $errors->first('course') }}</strong></span>
    @endif
    </div>
</div>

resources/views/enrolments/create.blade.php
@extends('layouts.app')
@section('content')
@include('layouts.admin')
<div class='container col-md-10'>
    <div class='row'>
            <div class='panel panel-default'>
                <div class='panel-heading'>Creación de Matrícula</div>
                <div class='panel-body'>
                    {!! Form::open(['route' => 'enrolments.store']) !!}
                        @include('enrolments.baseForm')
                        <div class='form-group'>
                            <div class='col-md-10'>
                                <button type='submit' id='btn_enrolment' class='btn btn-primary'><i class='glyphicon glyphicon-save'></i> Registrar</button>
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
    </div>
</div>
@endsection

resources/views/enrolments/edit.blade.php
@extends('layouts.app')
@section('content')
@include('layouts.admin')
<div class='container col-md-10'>
    <div class='row'>
            <div class='panel panel-default'>
                <div class='panel-heading'><b>Edición de Matrícula</b> <span class='glyphicon glyphicon-arrow-right'></span> {{$enrolment->name}}</div>
                <div class='panel-body'>
                    {!! Form::model($enrolment,['route' => ['enrolments.update',$enrolment->id],'method'=>'PUT']) !!}
                    @include('enrolments.baseForm')
                        <div class='form-group'>
                            <div class='col-md-10'>
                                <button type='submit' class='btn btn-primary'>
                                    <i class='glyphicon glyphicon-save'></i> Guardar
                                </button>
                            </div>
                        </div>
                        <div class='form-group'>
                            <div class='col-md-1'>
                                <a href="{{route('enrolments.index')}}" class='btn btn-primary' style='margin-left:10px'>
                                    <i class='glyphicon glyphicon-remove-sign'></i>Cancelar
                                </a>
                            </div>
                        </div>
                    {!!Form::close()!!}
                </div>
            </div> 
    </div>
</div>
@endsection

resources/views/enrolments/index.blade.php
@extends('layouts.app')
@section('content')
@include('layouts.admin')
<div class='success'></div>
<div class='container col-md-10'>

    <div class='col-md-3'>
    <a href="{{ route('enrolments.create') }}" ><span class='glyphicon glyphicon-plus'></span>Creación de Matrícula</a>
    </div>
    <a href="{{ url('enrolments/pdf') }}"><i class='fa fa-file-pdf-o' aria-hidden='true'></i> Lista de usuarios</a>
    
    <table class='table' id='myTable'>
        <thead><tr>
        <th>Matricula No.</th><th>Nombre</th><th>Apellido</th><th>Identificación</th><th>Curso</th><th>Estado</th><th>Acciones</th>  
        </tr></thead>

        <tbody>
            @foreach($enrolment as $field)<tr>
           <td>{{ $field->registration }}</td>
           <td>{{ $field->firstname }}</td>
           <td>{{ $field->lastname }}</td>
           <td>{{ $field->identification }}</td>
           <td>{{ $field->course }}</td>
           <td>{{ $field->payment_status }}</td>
           <td>
            <a href="{{ route('enrolments.edit',$enrolment->id) }}" title='Modificar'><span class='glyphicon glyphicon-pencil btn btn-primary' style='padding:1px 3px'></span></a>
            <a href="{{ url('enrolments/anulate',$enrolment->id) }}" title='Anular'><span class='glyphicon glyphicon-remove btn btn-primary' style='padding:1px 3px'></span></a>
            </td>
            
            </tr>
            @endforeach
        </tbody>        
    </table>
    <p><strong>Total registros activos: </strong>{{$total}}</p>
</div>  
@endsection

resources/views/enrolments/pdf.blade.php
@extends('layouts.app')
@section('content')
@include('layouts.admin')
    <table width='100%'>
        <thead><tr>
        <th>Matricula No.</th><th>Nombre</th><th>Apellido</th><th>Identificación</th><th>Curso</th><th>Estado</th><th>Acciones</th>  
        </tr></thead>

        <tbody>
            @foreach($enrolment as $field)<tr>
           <td>{{ $field->registration }}</td>
           <td>{{ $field->firstname }}</td>
           <td>{{ $field->lastname }}</td>
           <td>{{ $field->identification }}</td>
           <td>{{ $field->course }}</td>
           <td>{{ $field->payment_status }}</td>
            
            </tr>
            @endforeach
        </tbody>        
    </table>
    <p><strong>Total registros activos: </strong>{{$total}}</p>
</div>  
@endsection