app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();



Route::get('/home', 'HomeController@index');
Route::get('/aboutus', 'aboutusController@index');
Route::get('/courses', 'coursesController@index');
Route::resource('contact', 'contactController');
Route::resource('signup', 'studentController');
Route::resource('signup2', 'student2Controller');
Route::resource('interest_courses', 'interest_courses');
Route::get('paymentConfirmation', 'paymentConfirmationController@index');
Route::get('paymentSuccess', 'paymentConfirmationController@success');
Route::get('paymentRejected', 'paymentConfirmationController@rejected');
Route::get('paymentProcessed', 'paymentConfirmationController@proccesed');



Route::group(['middleware' => ['auth','admin']], function () {
    Route::resource('paymentRequest','paymentRequestController');

    /* Route::resource('forms','FormController');
    Route::get('studentslist','listController@students');
    Route::get('teacherslist','listController@teachers');
    Route::get('asessorslist','listController@assesors');
    Route::get('courses_shedule','listController@courses_shedule');
    //Route::resource('people','peopleController');
    Route::resource('students','studentsController');
    Route::get('students/enrolment/{id}','studentsController@enrolment');
    Route::resource('teachers','teachersController');
    Route::resource('courses_shedule','courses_sheduleController');
    Route::resource('enrolments','enrolmentController');
    //Route::get('students/enrolment/{id}','studentsController@enrolment'); */
});

Route::group(['middleware' => ['auth','assesor']], function () {
    
    Route::get('studentslist','listController@students');
    Route::resource('students','studentsController',['except'=>'create','edit','update']);
    //Route::get('students/enrolment/{id}','studentsController@enrolment');
});

app/Models/teacher.php
<?php

namespace oasis\Models;

use Illuminate\Database\Eloquent\Model;

class teacher extends Model
{
    protected $table="teachers";
    protected $fillable = [
        'person',
		];

    public function scopeName($query){
    	$query->select('teachers.id','person','people.lastname as lastname','id_types.name as id_type','id_types.id as id_type_key','people.identification as identification',
        'people.name as name','people.main_phone as main_phone','people.sec_phone as sec_phone','people.email as email','teachers.created_at as created_date','observations')
        ->join('people','people.id','=','teachers.person')
        ->join('id_types','id_types.id','=','people.id_type');
    }

    public function user()
	{
		return $this->bellongsTo(User::class);
	}

    	public function id_type()
	{
		return $this->bellongsTo(id_type::class);
	}
}

app/Http/Controllers/teachersController.php
<?php

namespace oasis\Http\Controllers;

use Illuminate\Http\Request;

use oasis\Http\Requests;
use oasis\Http\Requests\TeacherRequest;

use oasis\User;
use oasis\Models\teacher;
use oasis\Models\id_type;
use oasis\Models\course_category;
use oasis\Models\person;

use Mail;
use Session;
use Redirect;

class teachersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teachers=teacher::name()->get();
        $id_types=id_type::all();
        $course_categories=course_category::all();
        $people=person::all();
        //return $students;
        return [
            'teachers'=>$teachers,
            'id_types'=>$id_types,
            'course_categories'=>$course_categories,
            'people'=>$people
        ];
    }

    public function store(Request $request)
    {
       person::create($request->all());
       $item=person::where('identification',$request->identification)->first();
       teacher::create([
                'person' => $item->id,
                //'created_by'=>$request->user()->id
            ]);
       return;
       User::create([
            'name'=>$request->name,
            'email'=>$request->email,
            'role'=>'2',
            'password'=>bcrypt($request->identification)
       ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $teacher=teacher::name()->where('teachers.id',$id)->get();
        return view('teachers.details',compact('teacher'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        person::find($id)->update($request->all());
        return;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/teachers/baseForm.blade.php
<div class="col-md-6 form-group{{ $errors->has('name') ? ' has-error' : '' }}">
        <label for='name' class='col-md-12 control-label'>Nombres*</label>
        <div class='col-md-12'>
        <input required type='text' id='name' name='name' class='form-control' value="{{isset($student)?$student->name:old('name')}}">
         @if ($errors->has('name'))
            <span class='help-block'><strong>{{ $errors->first('name') }}</strong></span>
        @endif
        </div>
    </div>

    <div class="col-md-6 form-group{{ $errors->has('lastname') ? ' has-error' : '' }}">
        <label for='lastname' class='col-md-12 control-label'>Apellidos*</label>
        <div class='col-md-12'>
        <input required type='text' id='lastname' name='lastname' class='form-control' value="{{isset($student)?$student->lastname:old('lastname')}}">
         @if ($errors->has('lastname'))
            <span class='help-block'><strong>{{ $errors->first('lastname') }}</strong></span>
        @endif
        </div>
    </div>

    <div class="col-md-6 form-group{{ $errors->has('id_type') ? ' has-error' : '' }}">
        <label for='id_type' class='col-md-12 control-label'>Tipo de documento</label>
        <div class='col-md-12'>
       <select name='id_type' class='form-control'>
                @foreach($id_type as $field)
                @if((isset($student)&&$student->id_type==$field->id)||$field->id==old('id_type'))
                <option value="{{$field->id}}" selected>
                @else
                <option value="{{$field->id}}">
                @endif   
                    {{$field->name}}</option>
                @endforeach
           </select>
              @if ($errors->has('id_type'))
            <span class='help-block'><strong>{{ $errors->first('id_type') }}</strong></span>
        @endif
        </div>
    </div>


    <div class="col-md-6 form-group{{ $errors->has('identification') ? ' has-error' : '' }}">
        <label for='identification' class='col-md-12 control-label'>Identificación*</label>
        <div class='col-md-12'>
        <input required type='text' id='identification' name='identification' class='form-control' value="{{isset($student)?$student->identification:old('identification')}}">
         @if ($errors->has('identification'))
            <span class='help-block'><strong>{{ $errors->first('identification') }}</strong></span>
        @endif
        </div>
    </div>

    <div class="col-md-6 form-group{{ $errors->has('birthdate') ? ' has-error' : '' }}">
        <label for='birthdate' class='col-md-12 control-label'>Fecha de nacimiento</label>
        <div class='col-md-12'>
        <input type='date' id='birthdate' name='birthdate' class='form-control' value="{{isset($student)?$student->birthdate:old('birthdate')}}">
         @if ($errors->has('birthdate'))
            <span class='help-block'><strong>{{ $errors->first('birthdate') }}</strong></span>
        @endif
        </div>
    </div>

    <div class="col-md-6 form-group{{ $errors->has('email') ? ' has-error' : '' }}">
        <label for='email' class='col-md-12 control-label'>Correo electrónico*</label>
        <div class='col-md-12'>
        <input required type='email' id='email' name='email' class='form-control' value="{{isset($student)?$student->email:old('email')}}">
         @if ($errors->has('email'))
            <span class='help-block'><strong>{{ $errors->first('email') }}</strong></span>
        @endif
        </div>
    </div>

    <div required class="col-md-6 form-group{{ $errors->has('main_phone') ? ' has-error' : '' }}">
        <label for='main_phone' class='col-md-12 control-label'>Teléfono principal*</label>
        <div class='col-md-12'>
        <input type='number' id='main_phone' name='main_phone' class='form-control' value="{{isset($student)?$student->main_phone:old('main_phone')}}">
         @if ($errors->has('main_phone'))
            <span class='help-block'><strong>{{ $errors->first('main_phone') }}</strong></span>
        @endif
        </div>
    </div>

    <div class="col-md-6 form-group{{ $errors->has('sec_phone') ? ' has-error' : '' }}">
        <label for='sec_phone' class='col-md-12 control-label'>Teléfono alternativo</label>
        <div class='col-md-12'>
        <input type='number' id='sec_phone' name='sec_phone' class='form-control' value="{{isset($student)?$student->sec_phone:old('sec_phone')}}">
         @if ($errors->has('sec_phone'))
            <span class='help-block'><strong>{{ $errors->first('sec_phone') }}</strong></span>
        @endif
        </div>
    </div>

    <div class="col-md-6 form-group{{ $errors->has('interest_courses') ? ' has-error' : '' }}">
        <label for='interest_courses' class='col-md-12 control-label'>Cursos de interes*</label>
        <div class='col-md-12'>

            @foreach($course_category as $field)
            <div class='col-md-4'>
                <input class='' name='interest_courses[]' type='checkbox' value='{{$field->name}}'>{{$field->name}}
            </div>
            @endforeach

            @if ($errors->has('interest_courses[]'))
                <span class='help-block'><strong>{{ $errors->first('interest_courses[]') }}</strong></span>
            @endif
        </div>       
    </div>

    <div class="col-md-6 form-group{{ $errors->has('observations') ? ' has-error' : '' }}">
        <label for='observations' class='col-md-12 control-label'>Observaciones</label>
        <div class='col-md-12'>
        <textarea id='observations' name='observations' class='form-control'>{{isset($student)?$student->observations:old('observations')}}</textarea>
         @if ($errors->has('observations'))
            <span class='help-block'><strong>{{ $errors->first('observations') }}</strong></span>
        @endif
        </div>
    </div>
    
</div>

resources/views/teachers/create.blade.php
<form method="POST" v-on:submit.prevent="createItem">
<div class="modal fade" id="create">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
                <h4>Nuevo docente</h4>
            </div>
            <div class="modal-body">
                    <div class="col-md-6">
                        <label for='name' class='control-label'>Nombres*</label>
                        <input required type='text' name='name' v-model='c.name' class='form-control'>
                    </div>
                    
                    <div class="col-md-6">
                        <label for='lastname' class='control-label'>Apellidos*</label>
                        <input type='text' name='lastname' v-model='c.lastname' class='form-control'>
                    </div>

                    <div class="col-md-6">
                        <label for='id_type' class='control-label'>Tipo de documento*</label>
                        <select v-model="c.id_type" class="form-control" name='id_types'> 
                            <template v-for="item in id_types">
                                <option v-bind:value="item.id">
                                    @{{item.name}}
                                </option>
                            </template>
                            
                        </select>
                    </div>

                    <div class="col-md-6">
                        <label for='identification' class='control-label'>Número de documento*</label>
                        <input type='number' name='identification' v-model='c.identification' class='form-control'>
                    </div>

                    <div class="col-md-6">
                        <label for='birthdate' class='control-label'>Fecha de nacimiento*</label>
                        <input type='date' name='birthdate' v-model='c.birthdate' class='form-control'>
                    </div>

                    <div class="col-md-6">
                        <label for='email' class='control-label'>Correo electrónico*</label>
                        <input type='text' name='email' v-model='c.email' class='form-control' placeholder="example@mail.com">
                    </div>

                    <div class="col-md-6">
                        <label for='main_phone' class='control-label'>Teléfono principal*</label>
                        <input type='number' name='main_phone' v-model='c.main_phone' class='form-control'>
                    </div>
                    <div class="col-md-6">
                        <label for='sec_phone' class='control-label'>Teléfono alternativo</label>
                        <input type='number' name='sec_phone' v-model='c.sec_phone' class='form-control'>
                    </div>
                    
                    <div class="col-md-12">
                        <label for='observations' class='control-label'>Observaciones</label>
                        <textarea name='observations' v-model='c.observations' class='form-control'>
                            @{{e.observations}}
                        </textarea>    
                    </div>
            </div>
            <div class="modal-footer">
                <div class="col-md-6 col-md-offset-3">
                <input type="submit" class="btn btn-primary form-control" style="margin-top:10px" value="Guardar">
                </div>
            </div>
            
        </div>
        
    </div>
    
</div>
</form>

resources/views/teachers/details.blade.php
@extends('layouts.app')
@section('content')
@include('layouts.admin')
<div class='success'></div>
<div class='container col-md-10'>

    <div class='col-md-3'>
    <a href="{{ route('students.create') }}" ><span class='glyphicon glyphicon-plus'></span>Creación de Estudiante</a>
    </div>
    <a href="{{ url('students/pdf') }}"><i class='fa fa-file-pdf-o' aria-hidden='true'></i> Lista de usuarios</a>
    <h2>DATOS PERSONALES</h2>
    <table class='table' id='myTable'>

        <tbody>
            @foreach($student as $field)<tr>
            <?php
            $new = new DateTime($field->created_date);
            $pre_date=$new->format('d/m/Y \a \l\a\s h:m a');
            ?>
           <tr><th>Fecha de preinscripción:</td><td>{{ $pre_date }}</td></tr>
           <tr><th>Nombre completo:</td><td>{{ $field->name }} {{ $field->lastname }}</td></tr>
           <tr><th>Identificación:</th><td>{{ $field->id_type }} No. {{ $field->identification }}</td></tr>
           <tr><th>Teléfono principal</th><td>{{ $field->main_phone }}</td></tr>
           <tr><th>Teléfono secundario</th><td>{{ $field->sec_phone }}</td></tr>
           <tr><th>Correo electrónico</th><td>{{ $field->email }}</td></tr>
           <tr><th>Cursos de interés</th><td>{{ $field->interest_courses }}</td></tr>
           <tr><th>Observaciones</th><td>{{ $field->observations }}</td></tr>
           
            
            </tr>
            @endforeach
        </tbody>        
    </table>
    
</div>  
@endsection

resources/views/teachers/edit.blade.php
<div class="modal fade" id="edit">
<form method="POST" v-on:submit.prevent="updateItem(e.person)">    
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
                <h4>Editar estudiante</h4>
            </div>
            <div class="modal-body">
                    <div class="col-md-6">
                        <label for='name' class='control-label'>Nombres*</label>
                        <input required type='text' name='name' v-model='e.name' class='form-control'>
                    </div>
                    
                    <div class="col-md-6">
                        <label for='lastname' class='control-label'>Apellidos*</label>
                        <input type='text' name='lastname' v-model='e.lastname' class='form-control'>
                    </div>

                    <div class="col-md-6">
                        <label for='id_type' class='control-label'>Tipo de documento*</label>
                        <select v-model="e.id_type" class="form-control" name='id_type' > 
                            <template v-for="item in id_types">
                                <option v-bind:value="item.id">
                                    @{{item.name}}
                                </option>
                            </template>
                            
                        </select>
                    </div>

                    <div class="col-md-6">
                        <label for='identification' class='control-label'>Número de documento*</label>
                        <input type='number' name='identification' v-model='e.identification' class='form-control'>
                    </div>

                    <div class="col-md-6">
                        <label for='birthdate' class='control-label'>Fecha de nacimiento*</label>
                        <input type='date' name='birthdate' v-model='e.birthdate' class='form-control'>
                    </div>

                    <div class="col-md-6">
                        <label for='email' class='control-label'>Correo electrónico*</label>
                        <input type='text' name='email' v-model='e.email' class='form-control' placeholder="example@mail.com">
                    </div>

                    <div class="col-md-6">
                        <label for='main_phone' class='control-label'>Teléfono principal*</label>
                        <input type='number' name='main_phone' v-model='e.main_phone' class='form-control'>
                    </div>
                    <div class="col-md-6">
                        <label for='sec_phone' class='control-label'>Teléfono alternativo</label>
                        <input type='number' name='sec_phone' v-model='e.sec_phone' class='form-control'>
                    </div>
                    <div class="col-md-12">
                        <label for='observations' class='control-label'>Observaciones</label>
                        <textarea name='observations' v-model='e.observations' class='form-control'>
                            @{{e.observations}}
                        </textarea>    
                    </div>
                    
            </div>
            <div class="modal-footer">
                <div class="col-md-6 col-md-offset-3">
                <input type="submit" class="btn btn-primary form-control" style="margin-top:10px" value="Guardar">
                </div>
            </div>
            
        </div>
        
    </div>   
</form>
</div>

resources/views/teachers/index.blade.php
@extends('layouts.app')
@section('content')
@include('layouts.admin')



<div id="main" class="container col-md-10">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">

                    <div class="col-md-4">
                    <input type="search" v-model="search" placeholder="Buscar" class="form-control">
                    </div>
                    
                     <a href="#" class="btn btn-primary" v-on:click="searchItems(search)"><i class="glyphicon glyphicon-search"></i></a>
                    </form>
                    <a href="#" class="btn btn-primary pull-right" data-toggle="modal" data-target="#create">
                        <i class="glyphicon glyphicon-plus"></i>
                    </a>
                </div>

                <div class="panel-body">
                    <table class='table'>
        <thead><tr>
        <th>Acciones</th>
        <th>Nombre completo</th>
        <th>Teléfono principal</th>
         
        <th>Estado</th>  
        </tr></thead>
        <tbody>
            <tr v-for="item in list">
            <td>
            <a href="#" title='Ver detalles' v-on:click="showItem(item)"><span class='glyphicon glyphicon-eye-open btn btn-success' style='padding:1px 3px'></span></a>
            <a href="#" title='Modificar' v-on:click="editItem(item)"><span class='glyphicon glyphicon-pencil btn btn-primary' style='padding:1px 3px'></span></a>
            <a href="#" title='Matrícula' v-on:click="enrolment(item)"><span class='glyphicon glyphicon-list-alt btn btn-info' style='padding:1px 3px'></span></a>
            </td>
           <td>@{{ item.name }} @{{ item.lastname }}</td>
           <td>@{{ item.main_phone }}</td>
           <td>@{{ item.status }}</td>
            </tr>
            
        </tbody>        
    </table>
    </div>
</div><!--endPannel-->

            @include('teachers.create')
            @include('teachers.show')
            @include('teachers.edit')



        </div>
    </div>


    <pre>
        @{{$data}}
    </pre>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js" ></script>
<script src="{{asset('js/teachers.js')}}"></script>
@endsection

resources/views/teachers/pdf.blade.php
@extends('layouts.app')
@section('content')
@include('layouts.admin')
    <table width='100%'>
        <thead><tr>
        <th>Apellido</th><th>Nombre</th><th>Teléfono principal</th><th>Teléfono secundario</th><th>Correo electrónico</th><th>Cursos de interes</th><th>Acciones</th>  
        </tr></thead>

        <tbody>
            @foreach($student as $field)<tr>
           <td>{{ $field->lastname }}</td>
           <td>{{ $field->name }}</td>
           <td>{{ $field->main_phone }}</td>
           <td>{{ $field->sec_phone }}</td>
           <td>{{ $field->email }}</td>
           <td>{{ $field->interest_courses }}</td>
            
            </tr>
            @endforeach
        </tbody>        
    </table>
    <p><strong>Total registros activos: </strong>{{$total}}</p>
</div>  
@endsection

resources/views/teachers/show.blade.php
<div class="modal fade" id="show">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
                <h4>Datos personales</h4>
            </div>
            <div class="modal-body">
                    <table class="table table-hover">
                        <tbody>
                        <tr><th>Nombre completo:</th><td>@{{s.fullname}}</td></tr>
                        <tr><th>Tipo de documento:</th><td>@{{s.id_type}}</td></tr>
                        <tr><th>Número de documento:</th><td>@{{s.identification}}</td></tr>
                        <tr><th>Fecha de nacimiento:</th><td>@{{s.birthdate}}</td></tr>
                        <tr><th>Teléfono principal:</th><td>@{{s.main_phone}}</td></tr>
                        <tr><th>Teléfono alternativo:</th><td>@{{s.sec_phone}}</td></tr>
                        <tr><th>Email:</th><td>@{{s.email}}</td></tr>
                        <tr><th>Observations:</th><td>@{{s.observations}}</td></tr>
                    </tbody>
                       
                        
                    </table>
            </div>
            <div class="modal-footer">
                
            </div>
            
        </div>
        
    </div>
    
</div>